import "../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "../components/Navbar";
import Head from "next/head";
import { useEffect, useState } from 'react';

export default function App({ Component, pageProps }) {
  const [user, setUser] = useState(null);

  useEffect(() => {
    // Fetch user from localStorage when the component mounts
    const storedUser = localStorage.getItem('authUser');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
  }, []); // Dependency array ensures this runs only once on mount

  return (
    <>
      <Head>
        <title>Crud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username={user?.username} email={user?.email} />
      <Component {...pageProps} />
    </>
  );
}
